# Generated by Django 5.0.6 on 2024-07-13 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_salle', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='path/to/default/image.jpg', upload_to='media/')),
                ('date_publication', models.DateField(default=datetime.date.today)),
                ('disponible', models.CharField(choices=[('oui', 'oui'), ('non', 'non')], default='oui', max_length=4)),
                ('upload_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
