# Generated by Django 5.0.6 on 2024-07-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='media/'),
        ),
    ]
